### ISSUE TITLE
Missing exercise2 > final folder

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/mslearn-xamarin-forms-ui-with-xaml#1]
See following quote from [Exercise - Add behavior to your XAML page](https://docs.microsoft.com/en-us/learn/modules/create-ui-in-xamarin-forms-apps-with-xaml/8-exercise-add-behavior-to-your-xaml-page)
> You can view the completed solution in the exercise2 > final folder of your copy of the cloned or downloaded exercise repo.

Source code is missing in this repository.

**Comment by ghost** [comment]
After further investigation this could also be a typo. If so, the text "**exercise2 > final folder**" should be "**exercise1 > final folder**" and the "translationButton" in **MainPage.xaml** should be completed with a `Clicked` event.

        <Button x:Name="translateButton" Text="Translate"
                TextColor="{x:Static local:SharedResources.ButtonTextColor}"
                BackgroundColor="{x:Static local:SharedResources.ButtonBkColor}" Clicked="OnTranslate" />

**Comment by patridge** [comment]
Thanks for reporting this, @Sw1ma. I [fixed up the project breakdown in the exercise repo](https://github.com/MicrosoftDocs/mslearn-xamarin-forms-ui-with-xaml/pull/2) here. I also updated the exercise content to reflect that, as well as a few other fixes I found along the way.
